from datetime import datetime
from django.core.mail import EmailMessage


class Utility():

    @staticmethod
    def number_generator(prefix, id):
        date = '{:%Y%m%d}'.format(datetime.now())
        id_num = '{:07}'.format(id)
        autogenerated_no = str(prefix) + '-' + str(date) + '-' + str(id_num)

        return autogenerated_no

    @staticmethod
    def generate_code(model, prefix, id):
        code = Utility.number_generator(prefix, id)
        instance = model.objects.filter(id=id)
        instance.update(code=code)
        return instance.get()

    @staticmethod
    def send_email(data):
        email = EmailMessage(
            subject=data['email_subject'],
            body=data['email_body'],
            to=[data['to_email']])
        email.send()
